# Generated by Django 3.1 on 2023-07-11 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名')),
                ('winlose', models.TextField(verbose_name='勝敗')),
                ('perfect', models.TextField(verbose_name='perfect')),
                ('great', models.TextField(verbose_name='great')),
                ('good', models.TextField(verbose_name='good')),
                ('bad', models.TextField(verbose_name='bad')),
                ('miss', models.TextField(verbose_name='miss')),
                ('AP', models.TextField(verbose_name='AP')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('image', models.ImageField(upload_to='img/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
