# Generated by Django 3.1 on 2023-07-09 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名')),
                ('winlose', models.TextField(verbose_name='勝敗')),
                ('perfect', models.TextField(verbose_name='パーフェクト')),
                ('great', models.TextField(verbose_name='グレート')),
                ('good', models.TextField(verbose_name='グッド')),
                ('bad', models.TextField(verbose_name='バッド')),
                ('miss', models.TextField(verbose_name='ミス')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
