# Generated by Django 3.1 on 2023-07-13 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orc', '0003_auto_20230713_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('num', models.IntegerField(default=0, verbose_name='試合数')),
                ('win_ratio', models.IntegerField(default=0, verbose_name='勝率')),
                ('ap_ratio', models.IntegerField(default=0, verbose_name='AP率')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='APCount',
        ),
    ]
