# Generated by Django 3.1 on 2023-07-23 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orc', '0004_auto_20230713_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='曲名'),
        ),
        migrations.CreateModel(
            name='SongResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='曲名')),
                ('num', models.IntegerField(default=0, verbose_name='試合数')),
                ('win_ratio', models.IntegerField(default=0, verbose_name='勝率')),
                ('ap_ratio', models.IntegerField(default=0, verbose_name='AP率')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
